name: ${name}
version: ${version}
api-version: ${api_version}
main: ${main}
author: ${author}
website: ${website}
commands:
  psw:
    usage: /psw <bypass|reload|revoke>
permissions:
  psw.bypass:
    default: op
  psw.reload:
    default: op
  psw.revoke:
    default: op
